repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
    args: ['--unsafe','--allow-multiple-documents']
  - id: end-of-file-fixer
  - id: trailing-whitespace
  # - id: no-commit-to-branch
  #   args: ['--branch', 'master','--branch', 'main','--branch', 'staging']
  - id: check-added-large-files
    args: [— maxkb=1000]
  - id: check-symlinks
  - id: debug-statements
  # - id: detect-aws-credentials

-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
    -   id: reorder-python-imports
        args: [--py37-plus, --add-import, 'from __future__ import annotations']

-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.4.0
    hooks:
    -   id: add-trailing-comma
        args: [--py36-plus]

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        args: ['--line-length=90',]
        additional_dependencies: ['click==8.0.4']

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
        args: [--py310-plus]

-   repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0  # pick a git hash / tag to point to
    hooks:
    -   id: pydocstyle
        args: ["--convention=google"]

-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    - id: flake8
      language_version: python3
      args: ['--extend-ignore=E203', '--max-line-length=90']

# -   repo: local
#     hooks:
#       - id: jupyter-nb-clear-output
#         name: jupyter-nb-clear-output
#         files: \.ipynb$
#         stages: [commit]
#         language: system
#         entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace

# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v1.2.0
#     hooks:
#     -   id: mypy
#         additional_dependencies: [types-all]
#         exclude: ^testing/resources/
