name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:

    runs-on: ubuntu:focal

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . Dockerfile --tag rlbot:$(date +%s)
